In [1]:
import numpy as np

In [201]:
pokelist = np.genfromtxt("pokemons.csv", delimiter=",")
weight = np.genfromtxt("weight.csv",  delimiter=",")

print(pokelist, "\n")
print(weight)

[[1.5e+01 6.0e+00 2.5e+04 7.0e+00]
 [1.2e+01 7.0e+00 3.5e+04 7.0e+00]
 [1.0e+01 9.0e+00 5.5e+04 8.0e+00]] 

[0.3  0.05 0.6  0.05]


In [203]:
normalized_pokelist = np.sqrt((pokelist**2).sum(1))
normalized_pokelist.resize(normalized_pokelist.size, 1)

normalized_pokelist = pokelist / normalized_pokelist
print(normalized_pokelist)

result = np.dot(normalized_pokelist, weight)
print(result)

[[5.99999851e-04 2.39999940e-04 9.99999752e-01 2.79999931e-04]
 [3.42857109e-04 1.99999980e-04 9.99999901e-01 1.99999980e-04]
 [1.81818174e-04 1.63636357e-04 9.99999960e-01 1.45454540e-04]]
[0.60020585 0.6001228  0.60006998]


array([0.69263564, 0.69853547, 0.78772636, 0.62853936])